FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY target/*.jar app.jar
EXPOSE 8080
# JVM memory: 64m initial, 96m max
ENTRYPOINT ["java","-Xms64m","-Xmx96m","-XX:+UseContainerSupport","-jar","app.jar"]