spring.application.name=spring-boot
spring.datasource.url=${NOTIFICATION_DB_URL}
spring.datasource.username=${NOTIFICATION_DB_USERNAME}
spring.datasource.password=${NOTIFICATION_DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SENDER_EMAIL}
spring.mail.password=${SENDER_EMAIL_PASSWORD}
email.max-retries=3
email.retry-delay=300000

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}