FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY target/*.jar app.jar
EXPOSE 8080
# JVM memory: 96m initial, 128m max
ENTRYPOINT ["java","-Xms96m","-Xmx128m","-XX:+UseContainerSupport","-jar","app.jar"]