spring.application.name=spring-boot
spring.datasource.url=${BOOKING_DB_URL}
spring.datasource.username=${BOOKING_DB_USERNAME}
spring.datasource.password=${BOOKING_DB_PASSWORD}

spring.datasource.hikari.maximum-pool-size=${HIKARI_MAX_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${HIKARI_MIN_IDLE}
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.properties.hibernate.jdbc.prepare_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret =${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
services.resource.url=${RESOURCE_SERVICE_URL}
stripe.test.url=https://api.stripe.com/v1
stripe.test.secret=${STRIPE_TEST_SECRET}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
refund.retry.after=180
max.refund.retries=3

frontend.test.environment.url=http://localhost:4200
frontend.docker.url=http://localhost:8080
frontend.prod.environment.url=${APP_URL}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.virtual-host=${RABBITMQ_VHOST}

# Enable SSL/TLS
spring.rabbitmq.ssl.enabled=true