package com.example.springboot.model;

public enum MQEventType {
    BOOKING_CREATED,
    BOOKING_FAILED,
    BOOKING_CANCELED,
    BOOKING_CANCEL_FAILED,
    BOOKING_MODIFIED,
    BOOKING_MODIFY_FAILED,
    BOOKING_REFUND_FAILED,
    BOOKING_REFUNDED
}
