FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY target/*.jar app.jar
EXPOSE 8080
# JVM memory: 256m initial, 384m max
ENTRYPOINT ["java","-Xms256m","-Xmx384m","-XX:+UseContainerSupport","-jar","app.jar"]