spring.application.name=spring-boot
spring.datasource.url=${RESOURCE_DB_URL}
spring.datasource.username=${RESOURCE_DB_USERNAME}
spring.datasource.password=${RESOURCE_DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=${HIKARI_MAX_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${HIKARI_MIN_IDLE}
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.jpa.properties.hibernate.jdbc.prepare_sql=fals
