name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
      # 🔹 Temporary debug step
      - name: Decode GitHub OIDC token
        run: |
          echo "ID token payload:"
          echo $ACTIONS_ID_TOKEN | cut -d. -f2 | base64 --decode | jq
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1088612741231/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - run: gcloud auth configure-docker us-docker.pkg.dev

      - name: Build booking service
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/resource-repo/booking-service \
            -f ./booking-service/Dockerfile.deploy \
            ./booking-service
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/resource-repo/booking-service

      - name: Build resource service
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/resource-repo/resource-service \
            -f ./resource-service/Dockerfile.deploy \
            ./resource-service
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/resource-repo/resource-service

      - name: Build notification service
        run: |
          docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/resource-repo/notification-service \
            -f ./notification-service/Dockerfile.deploy \
            ./notification-service
          docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/resource-repo/notification-service
